# Generated by Django 2.2.5 on 2019-09-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20190923_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='planet',
            field=models.IntegerField(default=0),
        ),
    ]
