# Generated by Django 2.2.5 on 2019-09-23 18:04

from django.db import migrations

seed = {
    "0_0": {"coord_x": 0, "coord_y": 0, "north": None, "south": (0, -1), "east": (1, 0), "west": (-1, 0)}, "-1_0": {"coord_x": -1, "coord_y": 0, "north": (-1, 1), "south": (-1, -1), "east": (0, 0), "west": None}, "0_-1": {"coord_x": 0, "coord_y": -1, "north": (0, 0), "south": (0, -2), "east": (1, -1), "west": None}, "1_0": {"coord_x": 1, "coord_y": 0, "north": (1, 1), "south": (1, -1),
    "east": (2, 0), "west": (0, 0)}, "1_1": {"coord_x": 1, "coord_y": 1, "north": (1, 2), "south": (1, 0), "east": (2, 1), "west": None}, "-1_1": {"coord_x": -1, "coord_y": 1, "north": (-1, 2), "south": (-1, 0), "east": None, "west": (-2, 1)}, "2_1": {"coord_x": 2, "coord_y": 1, "north": None, "south": None, "east": (3, 1), "west": (1, 1)}, "3_1": {"coord_x": 3, "coord_y": 1, "north": (3, 2), "south": (3, 0), "east": (4, 1), "west": (2, 1)}, "1_-1": {"coord_x": 1, "coord_y": -1, "north": (1, 0), "south": None, "east": (2, -1), "west": (0, -1)}, "3_2": {"coord_x": 3, "coord_y": 2, "north": None, "south": (3, 1), "east": None, "west": None}, "0_-2": {"coord_x": 0, "coord_y": -2, "north": (0, -1), "south": None, "east": None, "west": (-1, -2)}, "-1_-2": {"coord_x": -1, "coord_y": -2, "north": (-1, -1), "south": (-1, -3), "east": (0, -2), "west": (-2, -2)}, "2_-1": {"coord_x": 2, "coord_y": -1, "north": (2, 0), "south": (2, -2), "east": None, "west": (1, -1)}, "-1_2": {"coord_x": -1, "coord_y": 2, "north": None, "south": (-1, 1), "east": None, "west": (-2, 2)}, "1_2": {"coord_x": 1, "coord_y": 2, "north": (1, 3), "south": (1, 1), "east": None, "west": None}, "4_2": {"coord_x": 4, "coord_y": 2, "north": (4, 3), "south": (4, 1), "east": (5, 2), "west": None}, "5_2": {"coord_x": 5, "coord_y": 2, "north": (5, 3), "south": None, "east": (6, 2), "west": (4, 2)}, "-1_-3": {"coord_x": -1, "coord_y": -3, "north": (-1, -2), "south": None, "east": (0, -3), "west": (-2, -3)}, "3_0": {"coord_x": 3, "coord_y": 0, "north": (3, 1), "south": None, "east": (4, 0), "west": None}, "5_3": {"coord_x": 5, "coord_y": 3, "north": (5, 4), "south": (5, 2), "east": (6, 3), "west": None}, "1_3": {"coord_x": 1, "coord_y": 3, "north": (1, 4), "south": (1, 2), "east": (2, 3), "west": (0, 3)}, "0_-3": {"coord_x": 0, "coord_y": -3, "north": None, "south": (0, -4), "east": (1, -3), "west": (-1, -3)}, "-2_1": {"coord_x": -2, "coord_y": 1, "north": (-2, 2), "south": None, "east": (-1, 1), "west": (-3, 1)}, "-2_2": {"coord_x": -2, "coord_y": 2, "north": None, "south": (-2, 1), "east": (-1, 2), "west": (-3, 2)}, "4_0": {"coord_x": 4, "coord_y": 0, "north": (4, 1), "south": None, "east": (5, 0), "west": (3, 0)}, "2_-2": {"coord_x": 2, "coord_y": -2, "north": (2, -1), "south": None, "east": (3, -2), "west": None}, "3_-2": {"coord_x": 3, "coord_y": -2, "north": None, "south": (3, -3), "east": None, "west": (2, -2)}, "-2_-2": {"coord_x": -2, "coord_y": -2, "north": None, "south": None, "east": (-1, -2), "west": (-3, -2)}, "3_-3": {"coord_x": 3, "coord_y": -3, "north": (3, -2), "south": (3, -4), "east": (4, -3), "west": None}, "4_-3": {"coord_x": 4, "coord_y": -3, "north": None, "south": (4, -4), "east":
    (5, -3), "west": (3, -3)}, "4_1": {"coord_x": 4, "coord_y": 1, "north": (4, 2), "south": (4, 0), "east": None, "west": (3, 1)}, "-3_-2": {"coord_x": -3, "coord_y": -2, "north": (-3, -1), "south": (-3, -3), "east": (-2, -2), "west": None}, "4_3": {"coord_x": 4, "coord_y": 3, "north": None, "south": (4, 2), "east": None, "west": None}, "-3_2": {"coord_x": -3, "coord_y": 2, "north": None, "south": None, "east": (-2, 2), "west": None}, "1_4": {"coord_x": 1, "coord_y": 4, "north": (1, 5), "south": (1, 3), "east": None, "west": (0, 4)}, "-3_-1": {"coord_x": -3, "coord_y": -1, "north": None, "south": (-3, -2), "east": None, "west": (-4, -1)}, "0_3": {"coord_x": 0, "coord_y": 3, "north": (0, 4), "south": None, "east": (1, 3), "west": (-1, 3)}, "-4_-2": {"coord_x": -4, "coord_y": -2, "north": (-4, -1), "south": (-4, -3), "east": None, "west": (-5, -2)}, "2_0": {"coord_x": 2, "coord_y": 0, "north": None, "south": (2, -1), "east": None, "west": (1, 0)}, "-3_-3": {"coord_x": -3, "coord_y": -3, "north": (-3, -2), "south": (-3, -4), "east": (-2, -3), "west": (-4, -3)}, "-2_-3": {"coord_x": -2, "coord_y": -3, "north": None, "south": None, "east": (-1, -3), "west": (-3, -3)}, "3_-4": {"coord_x": 3, "coord_y": -4, "north": (3, -3), "south": (3, -5), "east": None, "west": None}, "5_-3": {"coord_x": 5, "coord_y": -3, "north": (5, -2), "south": None, "east": None, "west": (4, -3)}, "2_3": {"coord_x": 2, "coord_y": 3, "north": None, "south": None, "east": None, "west": (1, 3)}, "0_-4": {"coord_x": 0, "coord_y": -4, "north": (0, -3), "south": (0, -5), "east": (1, -4), "west": (-1, -4)}, "-3_3": {"coord_x": -3, "coord_y": 3, "north": (-3, 4), "south": None, "east": (-2, 3), "west": (-4, 3)}, "-1_-1": {"coord_x": -1, "coord_y": -1, "north": (-1, 0), "south": (-1, -2), "east": None, "west": None}, "5_0": {"coord_x": 5, "coord_y": 0, "north": None, "south": None, "east": None, "west": (4, 0)}, "4_-4": {"coord_x": 4, "coord_y": -4, "north": (4, -3), "south": None, "east": None, "west": None}, "5_4": {"coord_x": 5, "coord_y": 4, "north": None, "south": (5, 3), "east": None, "west": None}, "3_-5": {"coord_x": 3, "coord_y": -5, "north": (3, -4), "south": (3, -6), "east": (4, -5), "west": (2, -5)}, "6_2": {"coord_x": 6, "coord_y": 2, "north": None, "south": (6, 1), "east": None, "west": (5, 2)}, "1_5": {"coord_x": 1, "coord_y": 5, "north": (1, 6), "south": (1, 4), "east": (2, 5), "west": None}, "3_-6": {"coord_x": 3, "coord_y": -6, "north": (3, -5), "south": None, "east": None, "west": None}, "-4_-3": {"coord_x": -4, "coord_y": -3, "north": (-4, -2), "south": None, "east": (-3, -3), "west": None}, "-5_-3": {"coord_x": -5, "coord_y": -3, "north": None, "south": (-5, -4), "east": None,
    "west": (-6, -3)}, "0_-5": {"coord_x": 0, "coord_y": -5, "north": (0, -4), "south": None, "east": (1, -5), "west": (-1, -5)}, "-1_3": {"coord_x": -1, "coord_y": 3, "north": (-1, 4), "south": None, "east": (0, 3), "west": (-2, 3)}, "-1_-4": {"coord_x": -1, "coord_y": -4, "north": None, "south": None, "east": (0, -4), "west": None}, "2_5": {"coord_x": 2, "coord_y": 5, "north": None, "south": (2, 4), "east": (3, 5), "west": (1, 5)}, "0_4": {"coord_x": 0, "coord_y": 4, "north": None, "south": (0, 3), "east": (1, 4), "west": (-1, 4)}, "2_4": {"coord_x": 2, "coord_y": 4, "north": (2, 5), "south": None, "east": (3, 4), "west": None}, "1_-5": {"coord_x": 1, "coord_y": -5, "north": (1, -4), "south": None, "east": (2, -5), "west": (0, -5)}, "2_-5": {"coord_x": 2, "coord_y": -5, "north": None, "south": None, "east": (3, -5), "west": (1, -5)}, "5_-2": {"coord_x": 5, "coord_y": -2, "north": (5, -1), "south": (5, -3), "east": (6, -2), "west": None}, "1_-3": {"coord_x": 1, "coord_y": -3, "north": None, "south": None, "east": None, "west": (0, -3)}, "-4_-4": {"coord_x": -4, "coord_y": -4, "north": None, "south": (-4, -5), "east": None, "west": (-5, -4)}, "3_4": {"coord_x": 3, "coord_y": 4, "north": (3, 5), "south": None, "east": None, "west": (2, 4)}, "1_-4": {"coord_x": 1, "coord_y": -4, "north": None, "south": (1, -5), "east": None, "west": (0, -4)}, "5_-1": {"coord_x": 5, "coord_y": -1, "north": None, "south": (5, -2), "east": None, "west": None}, "-5_-4": {"coord_x": -5, "coord_y": -4, "north": (-5, -3), "south": None, "east": (-4, -4), "west": None}, "3_5": {"coord_x": 3, "coord_y": 5, "north": None, "south": (3, 4), "east": (4, 5), "west": (2, 5)}, "4_-5": {"coord_x": 4, "coord_y": -5, "north": None, "south": None, "east": None, "west": (3, -5)}, "-5_-2": {"coord_x": -5, "coord_y": -2, "north": (-5, -1), "south": None, "east": (-4, -2), "west": None}, "6_-2": {"coord_x": 6, "coord_y": -2, "north": None, "south": None, "east": None, "west": (5, -2)}, "-6_-3": {"coord_x": -6, "coord_y": -3, "north": (-6, -2), "south": None, "east": (-5, -3), "west": None}, "6_3": {"coord_x": 6, "coord_y": 3, "north": None, "south": None, "east": None, "west": (5, 3)}, "-3_4": {"coord_x": -3, "coord_y": 4, "north": (-3, 5), "south": (-3, 3), "east": None, "west": None}, "1_6": {"coord_x": 1, "coord_y": 6, "north": (1, 7), "south": (1, 5), "east": (2, 6), "west": None}, "-1_4": {"coord_x": -1, "coord_y": 4, "north": (-1, 5), "south": (-1, 3), "east": (0, 4), "west": None}, "2_6": {"coord_x": 2,
    "coord_y": 6, "north": None, "south": None, "east": (3, 6), "west": (1, 6)}, "-6_-2": {"coord_x": -6, "coord_y": -2, "north": None, "south": (-6, -3), "east": None, "west": None}, "6_1": {"coord_x": 6, "coord_y": 1, "north": (6, 2), "south": None, "east": None, "west": None}, "3_6": {"coord_x": 3, "coord_y": 6, "north": None, "south": None, "east": None, "west": (2, 6)}, "-1_-5": {"coord_x": -1, "coord_y": -5, "north": None, "south": None, "east": (0, -5), "west": None}, "-5_-1": {"coord_x": -5, "coord_y": -1, "north": (-5, 0), "south": (-5, -2), "east": (-4, -1), "west": (-6, -1)}, "4_5": {"coord_x": 4, "coord_y": 5, "north": None, "south": None, "east": None, "west": (3, 5)}, "-4_3": {"coord_x": -4, "coord_y": 3, "north": None, "south": None, "east": (-3, 3), "west": (-5, 3)}, "-4_-1": {"coord_x": -4, "coord_y": -1, "north": None, "south": (-4, -2), "east": (-3, -1), "west": (-5, -1)}, "-4_-5": {"coord_x": -4, "coord_y": -5, "north": (-4, -4), "south": None, "east": (-3, -5), "west": None}, "-3_-4": {"coord_x": -3, "coord_y": -4, "north": (-3, -3), "south": (-3, -5), "east": None, "west": None}, "-2_4": {"coord_x": -2, "coord_y": 4, "north": None, "south": (-2, 3), "east": None, "west": None}, "-3_1": {"coord_x": -3, "coord_y": 1, "north": None, "south": None, "east": (-2, 1), "west": None}, "-2_3": {"coord_x": -2, "coord_y": 3, "north": (-2, 4), "south": None, "east": (-1, 3), "west": (-3, 3)}, "-3_-5": {"coord_x": -3, "coord_y": -5, "north": (-3, -4), "south": None, "east": None, "west": (-4, -5)}, "-5_3": {"coord_x": -5, "coord_y": 3, "north": None, "south": None, "east": (-4, 3), "west": None}, "-6_-1": {"coord_x": -6, "coord_y": -1, "north": None, "south": None, "east": (-5, -1), "west": None}, "1_7": {"coord_x": 1, "coord_y": 7, "north": None, "south": (1, 6), "east": None, "west": None}, "-1_5": {"coord_x": -1, "coord_y": 5, "north": None, "south": (-1, 4), "east": None, "west": None}, "-5_0": {"coord_x": -5, "coord_y": 0, "north": None, "south": (-5, -1), "east": None, "west": None}, "-3_5": {"coord_x": -3, "coord_y": 5, "north": None, "south": (-3, 4), "east": None, "west": None}
}

floor = 0


def make_rooms(apps, schema_editor):
    level = seed
    Room = apps.get_model("adventure", "Room")
    db_alias = schema_editor.connection.alias
    rooms = []
    for key in level:
        coord = key.split("_")
        rooms.append(
            Room(
                floor = floor,
                coord_x = coord[0],
                coord_y = coord[1]
            ),
        )

    Room.objects.using(db_alias).bulk_create(rooms)

def delete_rooms(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Room = apps.get_model("myapp", "Country")
    Room.objects.using(db_alias).delete()

def connect_rooms(apps, schema_editor):
    level = seed
    db_alias = schema_editor.connection.alias
    Room = apps.get_model("adventure", "Room")
    for key in level:
        coord = key.split("_")
        seed_room = level[key]
        db_room = Room.objects.using(db_alias).filter(
            floor = floor,
            coord_x = coord[0],
            coord_y = coord[1]
        )[0]
        for direc in ["north", "south", "east", "west"]:
            if seed_room[direc]:
                dest = Room.objects.using(db_alias).filter(
                    floor = floor,
                    coord_x = seed_room[direc][0],
                    coord_y = seed_room[direc][1]
                )[0]
                setattr(db_room, direc, dest.id)
        db_room.save()

class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_room_floor'),
    ]

    operations = [
        migrations.RunPython(make_rooms, delete_rooms),
        migrations.RunPython(connect_rooms)
    ]
