# Generated by Django 2.2.5 on 2019-09-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_seeding_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roomitem',
            name='respawn',
            field=models.DurationField(default=None),
        ),
    ]
